// Data.js
const DataForMonth6 = [
  {
    id: 0,
    images: [
      "cage",
      "Car",
      "Toy Car",
      "Hot Wheels",
      "Die Cast Toy",
      "Model Car",
      "Slot Car",
      "Collectible Car",
      "Micro Machine",
      "Matchbox Car",
      "Play Car",
      "Play Automobile",
      "Toy Vehicle",
    ],
    img: "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%201/Set6_Image1_Correct.svg",
    matched: false,
    option: [
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%201/Set6_Image1_Correct.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%201/Set6_Image1_Alt1.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%201/Set6_Image1_Alt2.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%201/Set6_Image1_Alt3.svg",
    ],
    missingImg:
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%201/Set6_Image1_Partial.svg",
    missingItem: [
      "Car",
      "Toy Car",
      "Hot Wheels",
      "Die Cast Toy",
      "Model Car",
      "Slot Car",
      "Collectible Car",
      "Micro Machine",
      "Matchbox Car",
      "Play Car",
      "Play Automobile",
      "Toy Vehicle",
    ],
    question: "What was in the cage?",
  },

  {
    id: 1,
    images: [
      "instrument",
      "Rubber Duck",
      "Rubber Ducky",
      "Floaty",
      "Squeaky",
      "Yellow Duck",
      "Tub Duck",
      "Tub Ducky",
      "Bath Duck",
      "Bath Ducky",
      "Plastic Duck",
      "Plastic Ducky",
      "Duck",
      "Ducky",
    ],
    img: "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%202/Set6_Image2_Correct.svg",
    matched: false,
    option: [
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%202/Set6_Image2_Correct.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%202/Set6_Image2_Alt1.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%202/Set6_Image2_Alt2.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%202/Set6_Image2_Alt3.svg",
    ],
    missingImg:
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%202/Set6_Image2_Partial.svg",
    missingItem: [
      "Rubber Duck",
      "Rubber Ducky",
      "Floaty",
      "Squeaky",
      "Yellow Duck",
      "Tub Duck",
      "Tub Ducky",
      "Bath Duck",
      "Bath Ducky",
      "Plastic Duck",
      "Plastic Ducky",
      "Duck",
      "Ducky",
    ],
    question: "What was in the instrument? ",
  },
  {
    id: 2,
    images: [
      "fishbowl",
      "Owl",
      "Hooter",
      "Madge",
      "Owlet",
      "Night Bird",
      "Barn Owl",
      "Horned Owl",
      "Snowy Owl",
    ],
    img: "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%203/Set6_Image3_Correct.svg",
    matched: false,
    option: [
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%203/Set6_Image3_Correct.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%203/Set6_Image3_Alt1.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%203/Set6_Image3_Alt2.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%203/Set6_Image3_Alt3.svg",
    ],
    missingImg:
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%203/Set6_Image3_Partial.svg",
    missingItem: [
      "Owl",
      "Hooter",
      "Madge",
      "Owlet",
      "Night Bird",
      "Barn Owl",
      "Horned Owl",
      "Snowy Owl",
    ],
    question: "What was in the fishbowl?",
  },
  {
    id: 3,
    images: ["basket", "Hanger", "Coat Hanger", "Clothes Hanger"],
    img: "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%204/Set6_Image4_Correct.svg",
    matched: false,
    option: [
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%204/Set6_Image4_Correct.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%204/Set6_Image4_Alt1.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%204/Set6_Image4_Alt2.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%204/Set6_Image4_Alt3.svg",
    ],
    missingImg:
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%204/Set6_Image4_Partial.svg",
    missingItem: ["Hanger", "Coat Hanger", "Clothes Hanger"],
    question: "What was on the basket?",
  },

  {
    id: 4,
    images: ["teacup", "Lightbulb", "Light", "Lamp"],
    img: "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%205/Set6_Image5_Correct.svg",
    matched: false,
    option: [
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%205/Set6_Image5_Correct.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%205/Set6_Image5_Alt1.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%205/Set6_Image5_Alt2.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%205/Set6_Image5_Alt3.svg",
    ],
    missingImg:
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month%206/Set%206%20Image%205/Set6_Image5_Partial.svg",
    missingItem: ["Lightbulb", "Light", "Lamp"],
    question: "What was in the teacup?",
  },
  {
    id: 5,
    images: ["cooler", "Coconut", "Coco", "Nut"],
    img: "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month 6/Set 6 Image 6/Set6_Image6_Correct.svg",
    matched: false,
    option: [
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month 6/Set 6 Image 6/Set6_Image6_Correct.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month 6/Set 6 Image 6/Set6_Image6_Alt1.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month 6/Set 6 Image 6/Set6_Image6_Alt2.svg",
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month 6/Set 6 Image 6/Set6_Image6_Alt3.svg",
    ],
    missingImg:
      "https://raw.githubusercontent.com/BIDMCDigitalPsychiatry/LAMP-activities/refs/heads/master/FunnyImages/Month 6/Set 6 Image 6/Set6_Image6_Partial.svg",
    missingItem: ["Coconut", "Coco", "Nut"],
    question: "What was in the cooler?",
  },
];
export default DataForMonth6;
