declare module '*.svg'
declare module '*.png'
declare module '*.jpg'
declare module 'react-router-dom'
declare module 'react-dom'
declare module 'react-addons-css-transition-group'
declare module 'react-animations'
declare module 'styled-components'
