name: Build Activities
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          ./build.sh
          git config --global user.name gh-actions
          git config --global user.email actions@github.com
          git commit -am "Publish activities for distribution"
          git push
