name: Build Activities
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          ./build.sh
      - uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: dist
          folder: dist
          clean: false
