name: Release
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name gh-actions
          git config --global user.email actions@github.com
          git checkout dist
          git tag -a -f latest -m 'latest' `git rev-parse --short HEAD`
          git push --force origin latest
